# Site settings
title: First Presbyterian Church of Beacon
remote_theme: mmistakes/minimal-mistakes@4.19.1
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/fpcbeacon/" # the subpath of your site, e.g. /blog/
url: "https://spartlow.github.io/fpcbeacon/" # the base hostname & protocol for your site
author: Copyright &copy; 2019 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
