# Site settings
title: First Presbyterian Church of Beacon
logo: /images/fpc_logo_website.png
#remote_theme: mmistakes/minimal-mistakes@4.19.1
remote_theme: mmistakes/minimal-mistakes
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/fpcbeacon/" # the subpath of your site, e.g. /blog/
url: "https://spartlow.github.io/fpcbeacon/" # the base hostname & protocol for your site
author: Copyright &copy; 2019 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
footer:
  links:
    - label: "50 Liberty Street Beacon NY"
      url: "https://maps.google.com/maps?ll=41.502589,-73.960129&z=16&t=m&hl=en&gl=US&mapclient=embed&cid=11269456934926098748"
    - label: "845-831-5322"
      url: "tel:845-831-5322"
    - label: "office@beaconpresbychurch.com"
      url: "mailto:office@beaconpresbychurch.com"
